# Generated by Django 5.0 on 2024-01-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Class_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Classroom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Coach_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Course_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Current_number_applicants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Full_number_applicants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Time_range',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Course_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Period',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
