# Generated by Django 5.0 on 2024-01-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0002_course_reservation_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_reservation',
            old_name='Time_range',
            new_name='Time_end',
        ),
        migrations.AddField(
            model_name='course_reservation',
            name='Time_start',
            field=models.DurationField(null=True),
        ),
    ]
