# Generated by Django 5.0 on 2024-01-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0003_rename_time_range_course_reservation_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Time_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Time_start',
            field=models.DateField(null=True),
        ),
    ]
