# Generated by Django 5.0 on 2024-01-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0004_alter_course_reservation_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Course_code',
            field=models.CharField(max_length=255, null='A11000A'),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Period',
            field=models.CharField(max_length=255, null='112-6期團課'),
        ),
    ]
