# Generated by Django 5.0 on 2024-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0005_alter_course_reservation_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Course_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Period',
            field=models.CharField(default='131213', max_length=255, null=True),
        ),
    ]
