# Generated by Django 5.0 on 2024-01-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0007_remove_course_reservation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_reservation',
            name='Course_name',
        ),
    ]
