# Generated by Django 5.0 on 2024-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0008_remove_course_reservation_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(help_text='課程類別', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Class_status',
            field=models.CharField(help_text='班級狀態，尚未達開班人數、已達開班人數、停開、僅現場報名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Classroom',
            field=models.CharField(help_text='教室', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Coach_name',
            field=models.CharField(help_text='教練名子', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Course_code',
            field=models.CharField(help_text='課程代碼', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Current_number_applicants',
            field=models.IntegerField(default=0, help_text='目前報名人數', null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Full_number_applicants',
            field=models.IntegerField(default=26, help_text='總共可報名的人數', null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Period',
            field=models.CharField(help_text='期別', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Time_end',
            field=models.DateField(help_text='結束日期', null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Time_start',
            field=models.DateField(help_text='開始日期', null=True),
        ),
    ]
