# Generated by Django 5.0 on 2024-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0009_alter_course_reservation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reservation',
            name='week',
            field=models.CharField(choices=[('星期一', '星期一'), ('星期二', '星期二'), ('星期三', '星期三'), ('星期四', '星期四'), ('星期五', '星期五'), ('星期六', '星期六'), ('星期日', '星期日')], default='星期一', max_length=10),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(help_text='課程名稱', max_length=255, null=True),
        ),
    ]
