# Generated by Django 5.0 on 2024-01-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0011_course_reservation_class_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='week',
            field=models.CharField(choices=[('星期一', '星期一'), ('星期二', '星期二'), ('星期三', '星期三'), ('星期四', '星期四'), ('星期五', '星期五'), ('星期六', '星期六'), ('星期日', '星期日')], default='', max_length=10),
        ),
    ]
