# Generated by Django 5.0 on 2024-01-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0012_alter_course_reservation_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(choices=[('基礎班', '基礎班'), ('進階班', '進階班'), ('大師班', '大師班')], help_text='課程名稱', max_length=255, null=True),
        ),
    ]
