# Generated by Django 4.2.10 on 2024-02-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course_reservation", "0013_alter_course_reservation_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_reservation_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Period", models.CharField(help_text="期別", max_length=255, null=True)),
                (
                    "Course_code",
                    models.CharField(help_text="課程代碼", max_length=255, null=True),
                ),
                (
                    "Student_id",
                    models.CharField(help_text="學生帳號", max_length=255, null=True),
                ),
                ("Create_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
