# Generated by Django 4.2.10 on 2024-02-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0014_course_reservation_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reservation_history',
            name='Coach_name',
            field=models.CharField(help_text='教練名子', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Class_status',
            field=models.CharField(help_text='班級狀態，報名中、開班中、報名已滿、停開、僅現場報名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation_history',
            name='Create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='建立時間'),
        ),
    ]
