# Generated by Django 4.2.10 on 2024-03-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0016_course_reservation_history_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(choices=[('Beginner Class', 'Beginner Class'), ('Intermediate Class', 'Intermediate Class'), ('Master Class', 'Master Class')], help_text='課程等級', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='Class_status',
            field=models.CharField(choices=[('Registration Open', 'Registration Open'), (' Registration Closed', ' Registration Closed'), ('Cancelled ', 'Cancelled '), ('On-site Registration Only', 'On-site Registration Only')], help_text='班級狀態，報名中、報名已滿、停開、僅現場報名', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course_reservation',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=10),
        ),
    ]
