# Generated by Django 4.2.10 on 2024-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0017_alter_course_reservation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='Category',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Master', 'Master')], help_text='課程等級', max_length=255, null=True),
        ),
    ]
