# Generated by Django 4.2.10 on 2024-05-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0019_course_reservation_history_class_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_reservation_history',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='', max_length=10),
        ),
    ]
