# Generated by Django 4.2.10 on 2024-05-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_reservation', '0020_course_reservation_history_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_reservation',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course_reservation_history',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=10),
        ),
    ]
