# Generated by Django 5.0.1 on 2024-05-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_survey_fill_in_3_alter_survey_fill_in_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question_1',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='在任何時候，我很清楚系統目前的狀態如何？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_10',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='我在使用這個系統時，不需要記憶太多東西，就可以完成任務？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_11',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='系統的顯示方式符合現實世界的習慣？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_2',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='在操作的過程中，網頁是否都有在合理的時間內做出回應？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_3',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='可以從每個頁面返回主頁嗎？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_4',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='是否能夠隨時取消和重做任何操作？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_5',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='對於系統的錯誤訊息是否都清楚明瞭？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_6',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='是否有清楚易懂的錯誤訊息？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_7',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='對於任何介面，使用一致的配色？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_8',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='對於任何介面，使用一致的排版？'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='question_9',
            field=models.CharField(choices=[('1', '非常不同意'), ('2', '不同意'), ('3', '中等'), ('4', '同意'), ('5', '非常同意')], max_length=1, verbose_name='網頁的排版設計遵循一般的網站標準嗎？'),
        ),
    ]
